import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  standalone: true,
  imports: [RouterOutlet],
  template: `<div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>
    <div>dashboard page123 dashboard</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export default class DashboardPageComponent {}
