export type AlertAppearance =
  | 'accent'
  | 'destructive'
  | 'error'
  | 'flat'
  | 'floating'
  | 'glass'
  | 'info'
  | 'link'
  | 'neutral'
  | 'opposite'
  | 'outline'
  | 'primary'
  | 'secondary'
  | 'success'
  | 'textfield'
  | 'warning'
  | 'whiteblock';
